# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Insall dependencies
      run: npm install 
    - name: Install newman & newman reporter
      run: | 
        npm install -g newman
        npm install -g newman-reporter-junitfull
    - name: Start up the API 
      run: | 
        npm start &
        sleep 75
    - name: Run the postman test aganist the api
      run: newman run "test/postman-coll.json" -r junitfull --reporter-junitfull-export 'newman/result.xml' -n 2
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "newman/**/*.xml"
    - name: Build It
      run: npm build 
